name: Deploy CI

on:
  push:
    branches: [ main ]
  repository_dispatch:
    branches: [ master ]
    types: [ update_post ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
      
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Build
        env:
          MICROCMS_API_KEY_BLOG: ${{ secrets.MICROCMS_API_KEY_BLOG }}
          MICROCMS_SERVICE_DOMAIN_BLOG: ${{ secrets.MICROCMS_SERVICE_DOMAIN_BLOG }}
          MICROCMS_API_KEY_PAGE: ${{ secrets.MICROCMS_API_KEY_PAGE }}
          MICROCMS_SERVICE_DOMAIN_PAGE: ${{ secrets.MICROCMS_SERVICE_DOMAIN_PAGE }}
          MICROCMS_API_KEY_NEWS: ${{ secrets.MICROCMS_API_KEY_NEWS }}
          MICROCMS_SERVICE_DOMAIN_NEWS: ${{ secrets.MICROCMS_SERVICE_DOMAIN_NEWS }}
          MICROCMS_API_KEY_OPT: ${{ secrets.MICROCMS_API_KEY_OPT }}
          MICROCMS_SERVICE_DOMAIN_OPT: ${{ secrets.MICROCMS_SERVICE_DOMAIN_OPT }}
          MICROCMS_API_KEY_NAV: ${{ secrets.MICROCMS_API_KEY_NAV }}
          MICROCMS_SERVICE_DOMAIN_NAV: ${{ secrets.MICROCMS_SERVICE_DOMAIN_NAV }}
        run: |
          npm ci
          npm run build --if-present
          
      - name: SSH Key Generate
        run: |
           mkdir -p ~/.ssh/
           echo "${{ secrets.SSH_PASSWORD }}" > ~/.ssh/id_ed25519
           chmod 600 ~/.ssh/id_ed25519
        
      - name: Deploy SSH
        run: rsync -ahvz -e "ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.SSH_PORT }} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" ./out/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_SERVER }}:${{ secrets.SSH_REMOTE_ROOT }} --include-from=".github/deploy_include.txt" --exclude-from=".github/deploy_exclude.txt"
